name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.8.0
      options: --user 1001

    steps:
    - name: clone
      uses: actions/checkout@v4
      with:
        submodules: recursive
      
    - name: build
      run: make
      
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: plugin
        path: ./*.3gx
