name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: pablomk7/libctrpf:0.7.4

    steps:
    - name: clone
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # should be done in the image instead
    - name: update
      run: dkp-pacman -Syu libctrpf --noconfirm
      
    - name: build
      run: make
      
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: ./*.3gx
